### ISSUE TITLE
How to pass Bundle to Fragments ?

### ISSUE THREAD

**Issue by cwoll87** [21Buttons/FragmentTestRule#11]
Usually when we use Fragments we pass Data to them via setBundle().
How can i achieve this in my Test Code when using this library ?

**Comment by BraisGabin** [comment]
override `createFragment` from `FragmentTestRule`

Something like this 

```java
    // I'm not sure if this compiles, but you can get the idea
    @Rule
    public FragmentTestRule<Activity, Fragment> activityRule = new FragmentTestRule<Activity, Fragment>(Activity.class, Fragment.class) {
        @Override
        protected Fragment createFragment() {
            return // create your fragment as you want
        }
    };
```

If you want to change the arguments between tests you should set `launchFragment` to `false` in the constructor and then use `FragmentTestRule.launchFragment(Fragment)` in your tests.

**Comment by cwoll87** [comment]
Thanks a lot for the quick and nice response. Just what i was looking for !
