### ISSUE TITLE
Support the new dagger-android library

### ISSUE THREAD

**Issue by RoRoche** [21Buttons/FragmentTestRule#2]
Does FragmentTestRule support the new dagger-android library?

Having a `Fragment` with the following code:

```java
public class FragmentA extends Fragment {

    @Inject
    public Dependency dependency;

    @Override
    public void onAttach(Context context) {
        AndroidSupportInjection.inject(this);
        super.onAttach(context);
    }
```

The corresponding `Activity` should embed a code as follows:

```java
public class MainActivity
        extends Activity
        implements HasSupportFragmentInjector {

    @Inject
    public DispatchingAndroidInjector<Fragment> supportFragmentInjector;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        AndroidInjection.inject(this);
        super.onCreate(savedInstanceState);
        // ...
    }

    @Override
    public AndroidInjector<Fragment> supportFragmentInjector() {
        return supportFragmentInjector;
    }
```

with all the `Modules` and `Subcomponents` necessary to configure Dagger 2 for Android support, as described in the [official documentation](https://google.github.io/dagger//android.html).

What is the proper to do so with FragmentTestRule?

**Comment by BraisGabin** [comment]
In this case your Fragment has a dependecy with your Activity. Your Fragment wants an Activity that implements `HasSupportFragmentInjector`.

You must create a `DebugActivity` that implements `HasSupportFragmentInjector` (preferebly in the debug variant). Add it to your AndroidManifest (preferebly in the debug variant too) and launch your Fragment with this activity:

```java
@Rule
public FragmentTestRule<DebugActivity, MyFragment> fragmentTestRule =
    new FragmentTestRule<>(DebugActivity.class, MyFragment.class);
```

You can check this post: https://engineering.21buttons.com/how-to-test-fragments-in-isolation-a7435a4cdc92 The second sample solves exactly this problem.
