### ISSUE TITLE
java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library

### ISSUE THREAD

**Issue by RoRoche** [21Buttons/FragmentTestRule#3]
In my Android library project, when using FragmentTestRule with the following configuration:

```groovy
compile 'com.android.support:appcompat-v7:26.+'
compile 'com.android.support.constraint:constraint-layout:1.0.2'
compile 'com.android.support:support-v4:26.+'
compile 'com.android.support:design:26.+'
```

I reach the following exception:

```
java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library
```

To solve it, I had to add a little more configuration in my `AndroidManifest.xml` file:

```xml
<manifest package="fr.guddy.android_modular_reloaded.first"
          xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppCompat.Light">
    </application>

</manifest>
```

since, by default, the `application` tag does not contain a `android:theme` attribute.
Maybe could it be mentioned in the README file.

**Comment by BraisGabin** [comment]
Are you using a custom `Activity`? Or this happen using the _default_ Activity?

If this happen using a custom Activity you can add the theme to that Activity as you do with the other Activities. If this happen using the _default_ Activity I think that I can fix it.

**Comment by RoRoche** [comment]
I'm using the default `Activity`.

**Comment by BraisGabin** [comment]
The close reason is at the PR.
