### ISSUE TITLE
FragmentTestRule could not found

### ISSUE THREAD

**Issue by daupawar** [21Buttons/FragmentTestRule#9]
Added this line in build.gradle

androidTestCompile 'com.21buttons:fragment-test-rule:1.0.0'

Inside MyUiAutomatorTest.Java

 @Rule
    public FragmentTestRule<?, MyVideoFragment> fragmentTestRule =
            FragmentTestRule.create(MyVideoFragment.class);

Error:- Could not resolve symbol 'FragmentTestRule'

**Comment by BraisGabin** [comment]
Is it in your `androidTest` directory? Did Android Studio find the import?

**Comment by daupawar** [comment]
Yes, it's androidTest` directory.

**Comment by BraisGabin** [comment]
I can't imagine why this is happening... Can you create a mini project to reproduce this error?

**Comment by daupawar** [comment]
Okay,  I will create

**Comment by BraisGabin** [comment]
If you have any update on this issue, please open it again. Meanwhile I'm going to close it.
